name: test-workflow
run-name: Testing parser output

on:
  push:
        branches:
            - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install xmake
        run: |
          curl -fsSL https://xmake.io/shget.text | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build project
        run: xmake -y

      - name: Run tests
        run: xmake run tests